# Generated by Django 2.2.3 on 2019-07-18 09:52

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(help_text='Title Of Box', max_length=255, verbose_name='Title')),
                ('position_x', models.FloatField(blank=True, default=0, verbose_name='position x')),
                ('position_y', models.FloatField(blank=True, default=0, verbose_name='position y')),
                ('width', models.FloatField(blank=True, default=100, null=True, verbose_name='box_width')),
                ('height', models.FloatField(blank=True, default=100, null=True, verbose_name='box_height')),
            ],
            options={
                'verbose_name': 'Box',
                'verbose_name_plural': 'Boxes',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='box',
            index=models.Index(fields=['title'], name='boxes_box_title_104144_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='box',
            unique_together={('id', 'title')},
        ),
    ]
